import img from "../../assets/images/cate1.png";

export const pages_items = [
  {
    _id: 1,
    name: "Graphic Designer",
    slug: "graphic-designer",
    img: img,
    createdAt: "Jan 16 2024",
    status: "Publish",
  },
  {
    _id: 2,
    name: "Website Design",
    slug: "website-design",
    img: img,
    createdAt: "Jan 16 2024",
    status: "Publish",
  },
  {
    _id: 3,
    name: "Brand Design",
    slug: "brand-design",
    img: img,
    createdAt: "Jan 16 2024",
    status: "Publish",
  },
  {
    _id: 4,
    name: "Logo Enhancement",
    slug: "logo-enhancement",
    img: img,
    createdAt: "Jan 16 2024",
    status: "Publish",
  },
  {
    _id: 5,
    name: "T-Shirt Design",
    slug: "t-shirt-design",
    img: img,
    createdAt: "Jan 16 2024",
    status: "Publish",
  },
  {
    _id: 6,
    name: "Logo Inspiration",
    slug: "logo-inspiration",
    img: img,
    createdAt: "Jan 16 2024",
    status: "Publish",
  },
  {
    _id: 7,
    name: "Longhorn Logos",
    slug: "longhorn-logos",
    img: img,
    createdAt: "Jan 16 2024",
    status: "Publish",
  },
  {
    _id: 8,
    name: "Mascot Logo",
    slug: "mascot-logo",
    img: img,
    createdAt: "Jan 16 2024",
    status: "Publish",
  },
];
